---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart chrony
  service:
    name: chronyd
    state: restarted
  when: molecule_yml is not defined

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: reboot for selinux
  reboot:
    msg: "Rebooting to apply SELinux disable"
    test_command: "getenforce"
  when: molecule_yml is not defined
