---
- name: ntp setup
  block:
    - name: Install chrony
      dnf:
        name: chrony
        state: present

    - name: backup original chrony/chrony.conf.j2
      copy:
        src: /etc/chrony.conf
        dest: /etc/chrony.conf.org
        remote_src: yes
        mode: '0644'
      when: molecule_yml is not defined

    - name: Deploy chrony configuration
      template:
        src: chrony/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart chrony

    - name: Enable and Restart chrony.service
      service:
        name: chronyd
        state: started
        enabled: yes
      when: molecule_yml is not defined

  tags:
    - common
    - common_ntp_setup
