stages:
#  - build
  - lint
  - test

#build_docker_image:
#  stage: build
#  image: docker:latest
#  services:
#    - docker:dind
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_TLS_CERTDIR: ""
#  script:
#    - docker build -t molecule_rockylinux -f Dockerfile.rockylinux8 .

lint:
  stage: lint
  image: python:3.9
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - pip install ansible ansible-lint flake8 yamllint
  script:
    - yamllint .
    - ansible-lint .
  only:
    - main
    - /^feature\/.*$/

molecule_test:
  stage: test
  image: python:3.9
  #alias: docker
  #image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    ANSIBLE_ROLES_PATH: /gitlab/roles
  before_script:
    - apt-get update && apt-get install -y rsync python3 python3-pip sshpass libvirt-dev gcc libssl-dev libffi-dev docker.io
    - docker build -t molecule_rockylinux -f Dockerfile.rockylinux8 .
    - pip install pipenv
    - pipenv install --deploy --dev
    #- export ANSIBLE_ROLES_PATH=/gitlab/ansible_roles # ansible_roles＝roles
  script:
    #- cd roles/common
    - pipenv run molecule test

  only:
    - main
    - /^feature\/.*$/