---
dependency:
  name: galaxy
driver:
  name: docker    # ドライバーはデフォルトでDocker
#lint:
#  name: yamllint    # LintツールはデフォルトでYamllint
platforms:
  - name: instance
    image: molecule_rockylinux
    pre_build_image: true         # 既存image利用、設定しないとmoleculeは自動で再build
    privileged: true              # systemd利用権限
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
#  lint:
#    name: ansible-lint
  config_options:
    defaults:
      roles_path: /gitlab/roles

verifier:
  name: testinfra    # デフォルトはAnsible
#  lint:
#    name: flake8